config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'articles#index'

  resources :articles, only: %i[index show]
  resource :profile, controller: 'profile', only: :show
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil) # rubocop:disable Lint/UnusedMethodArgument
    %w[
      created_at
      email
      encrypted_password
      id
      id_value
      remember_created_at
      reset_password_sent_at
      reset_password_token
      updated_at
    ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  MAXIMUM_LENGTH_FOR_TITLE = 124
  MAXIMUM_LENGTH_FOR_SUMMARY = 1024
  MAXIMUM_LENGTH_FOR_CONTENT = 30_000

  validates :title, :summary, :content, presence: true
  validates :title, length: { maximum: MAXIMUM_LENGTH_FOR_TITLE }
  validates :summary, length: { maximum: MAXIMUM_LENGTH_FOR_SUMMARY }
  validates :content, length: { maximum: MAXIMUM_LENGTH_FOR_CONTENT }

  def self.ransackable_attributes(auth_object = nil) # rubocop:disable Lint/UnusedMethodArgument
    %w[content created_at id id_value summary title updated_at]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  before_validation :generate_temporary_password, on: :create
  # after_commit :send_temporary_password

  validates :nickname, presence: true, length: { minimum: 3, maximum: 8 }, uniqueness: true

  protected

  def after_confirmation
    send_temporary_password
  end

  private

  def generate_temporary_password
    return unless password.blank?

    self.password = Devise.friendly_token.first(8)
    self.password_confirmation = password
  end

  def send_temporary_password
    UserMailer.with(user: self).temporary_password_email.deliver_now
  end
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  include Pundit::Authorization
  include DevisePermittedParameters
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html

  def index
    @articles = Article.all
    respond_with(@articles)
  end

  def show
    @article = Article.find(params[:id])
    respond_with(@article)
  end
end

app/controllers/concerns/devise_permitted_parameters.rb
module DevisePermittedParameters
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    return unless flash.present?

    flash.each do |type, message|
      if type == 'notice'
        return content_tag(:p, message, style: 'color: green;')
      elsif type == 'alert'
        return content_tag(:p, message, style: 'color: red;')
      end
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def action_method
    if params[:action] == 'new'
      :post
    else
      :patch
    end
  end
end

app/views/articles/_article.slim
div id= "#{ dom_id(article) }"
.card.mt-4
  div.card-body
    i.bi.bi-alarm(style='font-size: 2rem; color: cornflowerblue;')
    h2.card-title.text-left
      = article.title
    br
    hr
    p.card-text id='article-content'
      = article.content

javascript:
  marked.setOptions({
    sanitize: true
  });

  document.getElementById('article-content').innerHTML = marked.parse('#{ j article.content }');

app/views/articles/_preview_article.slim
div
  h2 = article.title
  br
  hr
  p id="article#{ article.id }"
    = article.summary

javascript:
  marked.setOptions({
    sanitize: true
  });

  document.getElementById('article#{ article.id }').innerHTML = marked.parse('#{ j article.summary }');

app/views/articles/index.slim
.p-5.mb-4.bg-body-tertiary.rounded-3
  .container-fluid.py-5
    h1.display-5.fw-bold Custom jumbotron
    p.col-md-8.fs-4 Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.

#articles
  - @articles.each_with_index do |article, index|
    .row.align-items-stretch
      .col-12.m-1
        - if index.even?
          .h-100.p-5.text-bg-secondary.border.rounded-3
            = render 'preview_article', article: article
            = link_to 'Show this article', article, class: 'btn btn-outline-light btn-sm'
        - else
          .h-100.p-5.bg-body-secondary.border.rounded-3
            = render 'preview_article', article: article
            = link_to 'Show this article', article, class: 'btn btn-outline-secondary btn-sm'

app/views/articles/show.slim
div
  = link_to 'Back to articles', articles_path, class: 'btn btn-secondary btn-sm'

= render @article

app/views/layouts/application.slim
doctype html
html
  head
    title MyBlog
    meta name='viewport' content='width=device-width,initial-scale=1'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', "data-turbo-track": 'reload'
    = javascript_importmap_tags

     / CDN подключение simplemde (форма для создания статьи в формате md)
    link rel='stylesheet' href='https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css'
    script src='https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js'

     / CDN подключение marked (отображение статьи в формате md)
    script src='https://cdn.jsdelivr.net/npm/marked/marked.min.js'

  body
    .container.py-4
      header.pb-3.mb-4.border-bottom
        - if user_signed_in?
          .btn-group.float-end
            = link_to 'Профиль', profile_path, class: 'btn btn-primary me-2 float-end'
            = button_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-primary float-end'
        - else
          .btn-group.float-end
            = link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn btn-primary me-1 float-end'
            = link_to 'Войти', new_user_session_path, class: 'btn btn-primary float-end'
        a.d-flex.align-items-center.text-body-emphasis.text-decoration-none href="#{ root_path }"
          span.fs-4 Developer Blog

      = flash_message
      = yield

      footer.pt-3.mt-4.text-body-secondary.border-top
        | &copy; 2023

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>